### ISSUE TITLE
How to install on windows?

### ISSUE THREAD

**Issue by rjsr213** [asg017/sqlite-vss#29]
I used pip install sqlite vss and it gave me an error, I searched to install it manually in site-packages and I only found it for mac and linux

**Comment by asg017** [comment]
Follow #15 for updates: `sqlite-vss` has to be pre-compiled for Windows, but it's currently very difficult to compile it on the github actions windows runner. It'll be done eventually, but I don't have a timeline yet.

In the meantime, consider WSL2
