### ISSUE TITLE
Could not find a declaration file for module 'sqlite-vss'.

### ISSUE THREAD

**Issue by linonetwo** [asg017/sqlite-vss#41]
Seems this is written in typescript, but not bundle .d.ts file within npm package? Can you include it?

Thanks in advance.

**Comment by linonetwo** [comment]
This may work:

```ts
declare module 'sqlite-vss' {
  export interface Database {
    // after https://deno.land/x/sqlite3@0.8.0/mod.ts?s=Database#method_loadExtension_0
    loadExtension(file: string, entrypoint?: string | undefined): void;
  }

  /**
   * Loads the sqlite-vss extension on the given sqlite3 database.
   */
  export function loadVector(database: Database): void;
  /**
   * Loads the sqlite-vss extension on the given sqlite3 database.
   */
  export function loadVss(database: Database): void;

  /**
   * Loads the sqlite-vss extension on the given sqlite3 database.
   */
  export function load(database: Database): void;
}
```

**Comment by asg017** [comment]
Hey @linonetwo , [`v0.1.1-alpha.9`](https://github.com/asg017/sqlite-vss/releases/tag/v0.1.1-alpha.9) just published with the `.d.ts` types you added - can you give it a try and lmk if it works as expected?

**Comment by linonetwo** [comment]
Yes it works, thanks for rapid update.

**Comment by linonetwo** [comment]
I was on Windows PC last few days, back on Mac today.

**Comment by linonetwo** [comment]
Sorry, but the .d.ts file isn't publish to npm, maybe we need to change 

https://github.com/asg017/sqlite-vss/blob/ca4aeb318ddc213504cabe6732735b6c7e3a21cc/bindings/node/sqlite-vss/package.json.tmpl#L18-L22

to add it. But should I also add index.js too?

**Comment by asg017** [comment]
@linonetwo  [`v0.1.1-alpha.17`](https://www.npmjs.com/package/sqlite-vss/v/0.1.1-alpha.17) now includes the `.d.ts` file in `files`, can you give it a shot?

**Comment by linonetwo** [comment]
Thanks, this works
![截屏2023-06-07 11 27 10](https://github.com/asg017/sqlite-vss/assets/3746270/8f7e36b6-c284-47de-98d6-20d9f772beb6)

**Comment by linonetwo** [comment]
Sorry but I finally decided to copy code and managed in my codebase, because the path from `loadablePathResolver` maybe incorrect after electron app packaged. (It will be `.webpack/main/index.js` in other folder instead of in node_modules folder.)

**Comment by linonetwo** [comment]
I'm trying to add this to https://github.com/tiddly-gittly/TidGi-Desktop , to provide note search. Thank you for your library!
