### ISSUE TITLE
optionalDependency not installed by pnpm

### ISSUE THREAD

**Issue by linonetwo** [asg017/sqlite-vss#43]
Seems `pnpm i sqlite-vss` won't install `sqlite-vss-darwin-x64` on my MacBook Pro 16-inch, 2019

```sh
% pnpm ls sqlite-vss-darwin-x64                       
% pnpm ls sqlite-vss           
Legend: production dependency, optional only, dev only

dependencies:
sqlite-vss 0.1.1-alpha.8
```

![截屏2023-05-29 00 00 54](https://github.com/asg017/sqlite-vss/assets/3746270/ab904ef4-8774-4fbe-827f-e306e06a3a21)

**Comment by asg017** [comment]
Can you try running this in your project?

```
pnpm config set auto-install-peers true --location .
```

Seems like pnpm handles peer dependencies oddly, but I think this should fix it? If it works for you I'll add a notice to the documentation

**Comment by linonetwo** [comment]
Sorry but this doesn't work either...

Also this doesn't create any config file on folder.

**Comment by linonetwo** [comment]
Well, I can't let this problem hold my leg, adding these to my project's package.json solves this as a workaround:

```json
  "optionalDependencies": {
    "sqlite-vss-darwin-x64": "0.1.1-alpha.13",
    "sqlite-vss-darwin-arm64": "0.1.1-alpha.13",
    "sqlite-vss-linux-x64": "0.1.1-alpha.13"
  },
```
