### ISSUE TITLE
can't add more than a single row

### ISSUE THREAD

**Issue by radekosmulski** [asg017/sqlite-vss#91]
I am running into a very peculiar problem -- I cannot add more than a single row to a table... it always ends in a `OperationalError: SQL logic error`.

For instance, the following code:

```
import sqlite3
import sqlite_vss

db = sqlite3.connect(':memory:')
db.enable_load_extension(True)
sqlite_vss.load(db)
db.enable_load_extension(False)

version, = db.execute('select vss_version()').fetchone()
print(version)

cur = db.cursor()


cur.execute("""
create virtual table vss_demo using vss0(
  a(3) factory="Flat,IDMap2" metrict_type=INNER_PRODUCT
);
""")

import json

embedding = [1.2, 0.3, 100]
cur.execute("insert into vss_demo(a) values (?)", [json.dumps(embedding)])

embedding = [1.2, 0.3, 120]
cur.execute("insert into vss_demo(a) values (?)", [json.dumps(embedding)])
```

will throw a `OperationalError: SQL logic error`.

Thank you very much for your help 🙏

**Comment by radekosmulski** [comment]
Interestingly, when I try reading from the table, I get the following error (and this is despite AFAICT I have followed the docs exactly)

![image](https://github.com/asg017/sqlite-vss/assets/2444926/f90d6ca1-f2d3-4b26-a9e8-5d2e6bbc46db)

**Comment by radekosmulski** [comment]
Thank you very much for your prompt reply, really appreciate it!!! 🙂

This does indeed fix the problem 🙏🥳

Unfortunately, I cannot overwrite a row, but that is not a big issue for my use case:
![image](https://github.com/asg017/sqlite-vss/assets/2444926/9c65127b-5853-4569-9c17-a6f9bb43c14b)

**Comment by radekosmulski** [comment]
Thank you so much for your help, @asg017! 🙏 Really appreciate your prompt replies and guidance!

**Comment by FrancoisThoraval** [comment]
Hi, I have the same issue. What is the current best practice to insert a new row when it's not possible to know the next rowid to insert ? 

I could work around something like querying the max rowid before each insertion, but doing this i'm unsure it will be safe with concurrency if another session is inserting while i'm getting the max rowid. Locking the table does not sound very practical either.
