### ISSUE TITLE
Can't install with pip on Windows

### ISSUE THREAD

**Issue by thewh1teagle** [asg017/sqlite-vss#96]
I tried to install this package on my `Windows 11` with `python3.8` or `python3.9`
in both I got this error:
```
(py38) C:\Users\User>pip install sqlite-vss
ERROR: Could not find a version that satisfies the requirement sqlite-vss (from versions: none)
ERROR: No matching distribution found for sqlite-vss
```

**Comment by asg017** [comment]
We don't have pre-compiled `sqlite-vss` binaries for Windows yet, which are used to build the python packages. See #15 for updates.

For now, you'll have to try to compile it yourself, or use WSL (in which case, the linux builds of `sqlite-vss` should work)
